#!/usr/bin/bash

ROOT_OUICHEFS=/mnt/PNLProject

insmod ~/share/PNLProject/ouichefs.ko
mkdir $ROOT_OUICHEFS

mount -o loop ~/share/PNLProject/mkfs/test.img $ROOT_OUICHEFS
mkdir $ROOT_OUICHEFS/dir/
mkdir $ROOT_OUICHEFS/dir/dir2/

# create 127 random files
for n in {1..127}; do
    touch $ROOT_OUICHEFS/dir/dir2/$( printf %03d "$n" ).txt
    dd if=/dev/urandom of=$ROOT_OUICHEFS/dir/dir2/$( printf %03d "$n" ).txt bs=1 count=$(( RANDOM + 1024 ));
    sync;
done

# make 001.txt the oldest file
touch -t 02020202 $ROOT_OUICHEFS/dir/dir2/001.txt

# check ouichefs does not remove a directory older than a file
mkdir $ROOT_OUICHEFS/dir/dir2/dir3
touch -t 01010101 $ROOT_OUICHEFS/dir/dir2/dir3

# insert the 129th link : ouichefs should remove 001.txt
touch $ROOT_OUICHEFS/dir/dir2/129.txt

echo "`ls $ROOT_OUICHEFS/dir/dir2 -F |grep -v / | wc -l` files in directory"
((ls $ROOT_OUICHEFS/dir/dir2 | grep 001.txt) && echo "Least recently used file still exists") || echo "Least recently used file removed correctly"


rm -rf $ROOT_OUICHEFS/*
umount $ROOT_OUICHEFS

rm -r $ROOT_OUICHEFS
rmmod ~/share/PNLProject/ouichefs.ko
