#!/usr/bin/bash

ROOT_OUICHEFS=/mnt/PNLProject

insmod ~/share/PNLProject/ouichefs.ko
mkdir $ROOT_OUICHEFS

mount -o loop ~/share/PNLProject/mkfs/test.img $ROOT_OUICHEFS
mkdir $ROOT_OUICHEFS/dir/
mkdir $ROOT_OUICHEFS/dir/dir2/


touch $ROOT_OUICHEFS/dir/dir2/$( printf %03d "1" ).txt
sync;

touch $ROOT_OUICHEFS/dir/dir2/$( printf %03d "1" ).txt
sync;


ls $ROOT_OUICHEFS/dir/dir2

rm -rf $ROOT_OUICHEFS/*
umount $ROOT_OUICHEFS

rm -r $ROOT_OUICHEFS
rmmod ~/share/PNLProject/ouichefs.ko    