#!/usr/bin/bash

ROOT_OUICHEFS=/mnt/PNLProject

insmod ~/share/PNLProject/ouichefs.ko
mkdir $ROOT_OUICHEFS

mount -o loop ~/share/PNLProject/mkfs/test.img $ROOT_OUICHEFS

mkdir $ROOT_OUICHEFS/dir{1..5}

for n in {1..2000}; do
    DIR=$ROOT_OUICHEFS/`ls $ROOT_OUICHEFS | sort -R | tail -1`
    touch $DIR/$( printf %04d "$n" ).txt;
    dd if=/dev/urandom of=$DIR/$( printf %04d "$n" ).txt bs=1 count=$(( RANDOM % 4000));
    sync;
done


rm -r $ROOT_OUICHEFS/*

umount $ROOT_OUICHEFS
rm -r $ROOT_OUICHEFS
rmmod ~/share/PNLProject/ouichefs.ko
