#!/usr/bin/bash

ROOT_OUICHEFS=/mnt/PNLProject

insmod ~/share/PNLProject/ouichefs.ko
mkdir $ROOT_OUICHEFS

mount -o loop ~/share/PNLProject/mkfs/test.img $ROOT_OUICHEFS
mkdir $ROOT_OUICHEFS/dir/
mkdir $ROOT_OUICHEFS/dir/dir2/

# check ouichefs does not remove a directory older than a file
mkdir $ROOT_OUICHEFS/dir/dir2/dir3
touch -t 01010101 $ROOT_OUICHEFS/dir/dir2/dir3

# create 4000 random files
for n in {1..4000}; do
    touch $ROOT_OUICHEFS/dir/dir2/$( printf %03d "$n" ).txt
    sync;
     #to differentiate the date of each file
    sleep 0.5;
done

ls $ROOT_OUICHEFS/dir/dir2

rm -rf $ROOT_OUICHEFS/*
umount $ROOT_OUICHEFS

rm -r $ROOT_OUICHEFS
rmmod ~/share/PNLProject/ouichefs.ko