#!/usr/bin/bash

ROOT_OUICHEFS=/mnt/PNLProject

insmod ~/share/PNLProject/ouichefs.ko
mkdir $ROOT_OUICHEFS

mount -o loop ~/share/PNLProject/mkfs/test.img $ROOT_OUICHEFS
mkdir $ROOT_OUICHEFS/dir/
mkdir $ROOT_OUICHEFS/dir/dir2/

for n in {1..100}; do
    touch $ROOT_OUICHEFS/dir/dir2/$( printf %03d "$n" ).txt
    dd if=/dev/urandom of=$ROOT_OUICHEFS/dir/dir2/$( printf %03d "$n" ).txt bs=1M count=$(( ( RANDOM % 4 )  + 1 ));
    sync;
done

ls $ROOT_OUICHEFS/dir/dir2

rm -rf $ROOT_OUICHEFS/*
umount $ROOT_OUICHEFS

rm -r $ROOT_OUICHEFS
rmmod ~/share/PNLProject/ouichefs.ko
