#!/usr/bin/bash


insmod ~/share/PNLProject/ouichefs.ko
mkdir /mnt/PNLProject

mount -o loop ~/share/PNLProject/mkfs/test.img /mnt/PNLProject
mkdir /mnt/PNLProject/dir/
mkdir /mnt/PNLProject/dir/dir2/

for n in {1..4}; do
    dd if=/dev/urandom of=/mnt/PNLProject/dir/dir2/$( printf %03d "$n" ).txt bs=1M count=$n;
    sync;
done


#echo -n a_function_non_defined /mnt/PNLProject/dir > /sys/kernel/ouichefs/ouichefs
#echo -n an_other_undefined /mnt/PNLProject/dir > /sys/kernel/ouichefs/ouichefs
#echo -n clear_a_file /mnt/PNLProject/notexists > /sys/kernel/ouichefs/ouichefs
echo -n clear_a_file /mnt/PNLProject > /sys/kernel/ouichefs/ouichefs
echo -n clear_a_file /mnt/PNLProject > /sys/kernel/ouichefs/ouichefs
echo -n clear_a_file_in_dir /mnt/PNLProject/dir/dir2 > /sys/kernel/ouichefs/ouichefs
echo -n clear_a_file_in_dir /mnt/PNLProject/dir/dir2 > /sys/kernel/ouichefs/ouichefs

rm -rf /mnt/PNLProject/*
umount /mnt/PNLProject

rm -r /mnt/PNLProject
rmmod ~/share/PNLProject/ouichefs.ko
