#!/usr/bin/bash


insmod ~/share/PNLProject/ouichefs.ko
mkdir /mnt/PNLProject

mount -o loop ~/share/PNLProject/mkfs/test.img /mnt/PNLProject
mkdir /mnt/PNLProject/dir/
mkdir /mnt/PNLProject/dir/dir2/

for n in {1..130}; do
    dd if=/dev/urandom of=/mnt/PNLProject/dir/dir2/$( printf %03d "$n" ).txt bs=1 count=$(( RANDOM + 1024 ));
done

rm -rf /mnt/PNLProject/*
umount /mnt/PNLProject

rm -r /mnt/PNLProject
rmmod ~/share/PNLProject/ouichefs.ko
